# Generated by Django 4.0 on 2022-11-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_members_id_alter_places_id_alter_services_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='id',
        ),
        migrations.AlterField(
            model_name='members',
            name='username',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
