# Generated by Django 4.0 on 2022-11-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_remove_members_id_alter_members_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=250)),
                ('count', models.IntegerField(default=5)),
                ('approval', models.CharField(choices=[('S', 'Success'), ('P', 'Pending'), ('R', 'Rejected')], max_length=250)),
            ],
        ),
    ]
