# Generated by Django 4.0 on 2022-11-12 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='count',
        ),
        migrations.AddField(
            model_name='booking',
            name='place',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='booking',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='car.members'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='approval',
            field=models.CharField(choices=[('S', 'Success'), ('P', 'Pending'), ('R', 'Rejected')], default='Pending', max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(default='', max_length=250),
        ),
    ]
